
#include "stdafx.h"

const TCHAR* kLevelDefault = _T("Unknown");

const TCHAR* kLevelsName[] = {
  NULL,
  _T("Glimer galleon"),
  _T("Rambi rumble"),
  _T("Pirate panic"),
  _T("Gangplank Galley"),
  _T("Rattle battle"),
  _T("Glimmer Galleon - Exit"),
  _T("Hot-head-top"),
  _T("Red-hot ride"),
  _T("Krow nest"),
  _T("Slime climb"),
  _T("Topsail trouble"),
  _T("Mainbrace mayhem"),
  _T("Kreepy Krow"),
  _T("Target terror"),
  _T("Rickety race"),
  _T("Haunted hall"),
  _T("Hornet Hole"),
  _T("Rambi Rumble - Rambi scene"),
  _T("Parrot Chute panic"),
  _T("Lava lagoon"),
  _T("Lockjaw locker"),
  _T("Fiery furnace"),
  _T("Web Woods"),
  _T("Gusty glade"),
  _T("Ghostly grove"),
  _T("Topsail trouble - Shortcut"),
  _T("K rool cabin"),
  _T("Hot Head top - Bonus 2"),
  _T("Pirate panic - Shortcut"),
  _T("Target terror - End"),
  _T("Web woods beta area"),
  _T("Mainbrace mayhem - Shortcut"),
  _T("Kleever kiln"),
  _T("Rattle battle - Rattly scene"),
  _T("Windy well"),
  _T("Sqwawks shaft"),
  _T("Kannon klaim"),
  _T("Parrot chute panic - Shortcut"),
  _T("Kannon klaim - Shortcut"),
  _T("Barrel Bayou"),
  _T("Krochead klamber"),
  _T("Web woods - Squitter scene"),
  _T("Barrel Bayou - Warp desabilitado"),
  _T("Mudhole marsh"),
  _T("Bramble blast"),
  _T("Bramble Scramble"),
  _T("Screech sprint"),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  _T("Wrinkly Kollege World 1"),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  _T("Swanky Bonus Bonanza World 1"),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  _T("Funky Flights"),
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  _T("King Zing sting"),
  _T("K.rool duel"),
  _T("Castle crush"),
  _T("Kudgel konquest"),
  NULL,
  NULL,
  NULL,
  NULL,
  _T("Lockjaw Locker - Shortcut"),
  _T("Lava Lagoon - Shortcut"),
  _T("Sqwawks Shaft - Shortcut"),
  _T("Kokodrile kore"),
  _T("Artic Abyss"),
  _T("Chain link chamber"),
  _T("Toxic Tower"),
  _T("Pirate panic - Bonus 1"),
  _T("Pirate panic - Bonus 2"),
  _T("Gangplank Galley - Bonus 2"),
  _T("Rattle Battle - Bonus 1"),
  _T("Rattle Battle - Bonus 3"),
  _T("Hot Heat Top - Bonus 3"),
  _T("Hot-Heat-Top - Bonus 1"),
  _T("Red-Hot-Ride - Bonus 1"),
  _T("Red-Hot-Ride - Bonus 2"),
  _T("Mainbrace Mayhem - Bonus 1"),
  _T("Mainbrace Mayhem - Bonus 2"),
  _T("Slime Climb - Bonus 1"),
  _T("Topsail Trouble - Bonus 1"),
  _T("Topsail Trouble - Bonus 2"),
  _T("Mainbrace Mayhem - Bonus 3"),
  _T("Slime Climb - Bonus 2"),
  _T("Rattle Battle - Bonus 2"),
  _T("Klobber Karnage"),
  _T("Lockjaw locker - Bonus 1"),
  _T("Glimmer Galleon - Bonus 2"),
  _T("Lava Lagoon - Bonus 1"),
  _T("Glimmer Galleon - Bonus 1"),
  _T("Ghostly grove - bonus 1"),
  _T("Gusty glade - Bonus 1"),
  _T("Gusty glade - Bonus 2"),
  _T("Ghostly grove Bonus 2"),
  _T("Barrel Bayou - Bonus 1"),
  _T("Barrel Bayou - Bonus 2"),
  _T("Krochead Klamber - Bonus 1"),
  _T("Mudhole Marsh - Bonus 1"),
  _T("Mudhole Marsh - Bonus 2"),
  _T("Hot-Heat-Top Red-Hot-ride - Shortcut"),
  _T("Clapper Cavern"),
  _T("Animal Antics - Enguarde Scene"),
  _T("Clapper Cavern - Bonus 1"),
  _T("Clapper Cavern - Bonus 2"),
  _T("Artic Abyss - Bonus 1"),
  _T("Black Ice Battle - Bonus 1"),
  _T("Artic Abyss - Bonus 2"),
  _T("Black Ice Battle"),
  _T("Klobber Karnage - Bonus 1"),
  _T("Jungle Jynx - Bonus 1"),
  _T("Jungle Jynx"),
  _T("Animal Antics - Rambi Scene"),
  _T("Animal Antics - Squitter Scene"),
  _T("Animal Antics - Rattly Scene"),
  _T("Animal Antics - Bonus 1"),
  _T("Fiery Furnace - Bonus 1"),
  _T("Animal Antics - Squawks Scene"),
  _T("Bramble Blast - Bonus 2"),
  _T("Target Terror - Bonus 1"),
  _T("Bramble Scramble - Bonus 1"),
  _T("Windy Well - Bonus 2"),
  _T("Web Woods - Bonus 1"),
  _T("Toxic Tower - Bonus 1"),
  _T("Bramble Blast - Bonus 1"),
  _T("Screech Sprint - Bonus 1"),
  _T("Gangplank galley - Bonus 1"),
  _T("Squawks Shaft - Bonus 3"),
  _T("Kannon Klaim - Bonus 3"),
  _T("Kannon Klaim - Bonus 1"),
  _T("Squawks Shaft - Bonus 1"),
  _T("Kannon Klaim - Bonus 2"),
  _T("Hornet Hole - Bonus 1"),
  _T("Parrot Chute Panic - Bonus 2"),
  _T("Hornet Hole - Bonus 3"),
  _T("Parrot Chute Panic - Bonus 1"),
  _T("Rambi Rumble - Bonus 2"),
  _T("Hornet Hole - Bonus 2"),
  _T("Rambi rumble - Bonus 1"),
  _T("Chain Link Chamber - Bonus 1"),
  _T("Chain Link Chamber - Bonus 2"),
  _T("Castle crush - Bonus 1"),
  _T("Castle crush - Bonus 2"),
  _T("Stronghold showdown"),
  _T("Squawks Shaft - Bonus 2"),
  _T("Web Woods - Bonus 2"),
  _T("Windy Well - Bonus 1"),
  _T("Haunted Hall - Bonus 1"),
  _T("Rickety Race - End"),
  _T("Haunted Hall - End"),
  _T("Haunted Hall Bonus 3"),
  _T("Target Terror - Bonus 2"),
  _T("Haunted Hall - Bonus 2"),
  _T("Rickety race - Bonus 1"),
};
